name: anylogicexperiments
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pytest
  - pylint
  - pyyaml
  - pandas
  - openpyxl
  - pip
  - pip:
      - https://cloud.anylogic.com/files/api-8.5.0/clients/anylogiccloudclient-8.5.0-py3-none-any.whl#egg=anylogiccloudclient
